Repository TaxRefundCalculator/TaxRefundCalculator, pull requests merged in 2025-06, with the labels that each got.

#28 Feat: 환급정보 보기 버튼 구현
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/Modals/CountryModal.swift
  TaxRefundCalculator/Modals/LanguageModal.swift
  TaxRefundCalculator/Modals/RefundModal.swift
  TaxRefundCalculator/Models/RefundCondition.swift
  TaxRefundCalculator/StartPage/StartPageVC.swift
  TaxRefundCalculator/TabBar/TabBarController.swift
Labels: Feat, UI

#47 Feat: 계산기록 저장하기 기능 구현, 영국 미국 지원 추가 및 예외처리
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/Modals/CountryModal.swift
  TaxRefundCalculator/Models/SaveUserDefaults.swift
  TaxRefundCalculator/Models/SavedCard.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
Labels: refactor, Feat

#48 Fix : 기록 구조 수정 중 임시 빌드
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/Models/SavedCard.swift
  TaxRefundCalculator/SavedPage/SavedCardCell.swift
  TaxRefundCalculator/SavedPage/SavedVC.swift
  TaxRefundCalculator/SavedPage/SavedVM.swift
Labels: fix, Warning

#54 Feat: 계산로직 구현
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/StartPage/StartPageVC.swift
Labels: Feat

#55 Fix: 기록탭 모델구조 수정 및 적용
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/Models/SaveUserDefaults.swift
  TaxRefundCalculator/Models/SavedCard.swift
  TaxRefundCalculator/SavedPage/SavedCardCell.swift
  TaxRefundCalculator/SavedPage/SavedModalVC.swift
  TaxRefundCalculator/SavedPage/SavedVC.swift
  TaxRefundCalculator/SavedPage/SavedVM.swift
  TaxRefundCalculator/SavedPage/SavedView.swift
  TaxRefundCalculator/Utils/DateUtils.swift
Labels: fix, Feat

#59 Feat: 다크모드, 기록초기화, 저장완료시 저장완료 Alert 띄우도록 구현
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/Models/SaveUserDefaults.swift
  TaxRefundCalculator/SceneDelegate.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/SettingPage/SettingVM.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
Labels: Feat

#67 Feat: 언어팩 기반 구현, 앱 아이콘 이미지 추가
  TaxRefundCalculator.xcodeproj/project.pbxproj
  TaxRefundCalculator/Assets.xcassets/AppIcon.appiconset/Contents.json
  TaxRefundCalculator/Assets.xcassets/AppIcon.appiconset/darkIcon.png
  TaxRefundCalculator/Assets.xcassets/AppIcon.appiconset/lightIcon.png
  TaxRefundCalculator/SavedPage/SavedCardCell.swift
  TaxRefundCalculator/SavedPage/SavedModalVC.swift
  TaxRefundCalculator/SavedPage/SavedView.swift
  TaxRefundCalculator/de.lproj/Localizable.strings
  TaxRefundCalculator/en.lproj/Localizable.strings
  TaxRefundCalculator/es.lproj/Localizable.strings
  TaxRefundCalculator/fr.lproj/Localizable.strings
  TaxRefundCalculator/it.lproj/Localizable.strings
  TaxRefundCalculator/ja.lproj/Localizable.strings
  TaxRefundCalculator/ko.lproj/Localizable.strings
  TaxRefundCalculator/ru.lproj/Localizable.strings
Labels: Feat

#69 Fix: 계산로직 국가별 숫자포맷 대응 기능 구현
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
Labels: fix

#73 Feat: 다국어 지원을 위한 로컬라이징 구현 및 언어선택 기능 삭제, 각종 버그 수정
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/ExchangePage/ExchangeView.swift
  TaxRefundCalculator/Modals/CountryModal.swift
  TaxRefundCalculator/Modals/LanguageModal.swift
  TaxRefundCalculator/Modals/RefundModal.swift
  TaxRefundCalculator/Models/CountryMatching.swift
  TaxRefundCalculator/Models/SaveUserDefaults.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/SettingPage/SettingVM.swift
  TaxRefundCalculator/StartPage/StartPageVC.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
  TaxRefundCalculator/de.lproj/Localizable.strings
  TaxRefundCalculator/en.lproj/Localizable.strings
  TaxRefundCalculator/es.lproj/Localizable.strings
  TaxRefundCalculator/fr.lproj/Localizable.strings
  TaxRefundCalculator/it.lproj/Localizable.strings
  TaxRefundCalculator/ja.lproj/Localizable.strings
  TaxRefundCalculator/ko.lproj/Localizable.strings
  TaxRefundCalculator/ru.lproj/Localizable.strings
Labels: bug, fix, refactor, Warning, Feat, UI

#82 Fix: 주석 정리, 구매금액 입력필드 예외처리 로직 리팩토링
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/Modals/CountryModal.swift
  TaxRefundCalculator/Modals/RefundModal.swift
  TaxRefundCalculator/Models/RefundCondition.swift
  TaxRefundCalculator/Models/SaveUserDefaults.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/SettingPage/SettingVM.swift
  TaxRefundCalculator/StartPage/StartPageVC.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
  TaxRefundCalculator/de.lproj/Localizable.strings
  TaxRefundCalculator/en.lproj/Localizable.strings
  TaxRefundCalculator/es.lproj/Localizable.strings
  TaxRefundCalculator/fr.lproj/Localizable.strings
  TaxRefundCalculator/it.lproj/Localizable.strings
  TaxRefundCalculator/ja.lproj/Localizable.strings
  TaxRefundCalculator/ko.lproj/Localizable.strings
  TaxRefundCalculator/ru.lproj/Localizable.strings
Labels: fix, refactor

#81 Fix: 기록모달VM 구현 및 전체 주석 수정
  TaxRefundCalculator/API/FirebaseExchangeService.swift
  TaxRefundCalculator/ExchangePage/ExchangeVM.swift
  TaxRefundCalculator/Models/RefundCondition.swift
  TaxRefundCalculator/SavedPage/SavedCardCell.swift
  TaxRefundCalculator/SavedPage/SavedModalVC.swift
  TaxRefundCalculator/SavedPage/SavedModalVM.swift
  TaxRefundCalculator/SavedPage/SavedVC.swift
  TaxRefundCalculator/SavedPage/SavedVM.swift
  TaxRefundCalculator/TabBar/TabBarController.swift
Labels: fix, Feat

#88 Fix: 다양한 숫자포맷 지원에 따른 버그 수정
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/SavedPage/SavedCardCell.swift
  TaxRefundCalculator/Utils/Double+Formatted.swift
Labels: bug, fix, Feat

#94 Feat: 시작화면 텍스트필드 중복입력 방지 예외처리 구현
  TaxRefundCalculator/StartPage/StartPageVC.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
  TaxRefundCalculator/de.lproj/Localizable.strings
  TaxRefundCalculator/en.lproj/Localizable.strings
  TaxRefundCalculator/es.lproj/Localizable.strings
  TaxRefundCalculator/fr.lproj/Localizable.strings
  TaxRefundCalculator/it.lproj/Localizable.strings
  TaxRefundCalculator/ja.lproj/Localizable.strings
  TaxRefundCalculator/ko.lproj/Localizable.strings
  TaxRefundCalculator/ru.lproj/Localizable.strings
Labels: Feat
