Repository TaxRefundCalculator/TaxRefundCalculator, pull requests merged in 2025-04, with the labels that each got.

#1 Feat: 기본 설정
  TaxRefundCalculator.xcodeproj/project.pbxproj
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/CalculatePage/CalculateView.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
  TaxRefundCalculator/StartPage/StartPageView.swift
Labels: documentation

#2 Feat: 폴더 및 파일 생성
  TaxRefundCalculator/SavedPage/SavedVC.swift
  TaxRefundCalculator/SavedPage/SavedVM.swift
  TaxRefundCalculator/SavedPage/SavedView.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/SettingPage/SettingVM.swift
  TaxRefundCalculator/SettingPage/SettingView.swift
Labels: documentation

#8 Feat: 컬러 에셋 추가
  TaxRefundCalculator/Assets.xcassets/bgPrimary.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/bgSecondary.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/bodyText.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/border.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/currency.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/downRed.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/mainTeal.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/placeholder.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/primaryText.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/subButton.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/subText.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/tabActive.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/tabInactive.colorset/Contents.json
  TaxRefundCalculator/Assets.xcassets/upGreen.colorset/Contents.json
Labels: UI

#11 Feat: 저장화면 및 임시탭바 UI 1차 구현
  TaxRefundCalculator/Extension/AddArrangedSubviews.swift
  TaxRefundCalculator/Extension/AddSubviews.swift
  TaxRefundCalculator/Models/SavedCard.swift
  TaxRefundCalculator/SavedPage/SavedCardCell.swift
  TaxRefundCalculator/SavedPage/SavedVC.swift
  TaxRefundCalculator/SavedPage/SavedView.swift
  TaxRefundCalculator/TabBar/TabBarController.swift
Labels: Feat, UI
