Repository TaxRefundCalculator/TaxRefundCalculator, pull requests merged in 2025-05, with the labels that each got.

#12 Feat: 실시간 환율탭 UI 1차 구현
  TaxRefundCalculator/ExchangePage/ExchangeCell.swift
  TaxRefundCalculator/ExchangePage/ExchangeModalVC.swift
  TaxRefundCalculator/ExchangePage/ExchangeVC.swift
  TaxRefundCalculator/ExchangePage/ExchangeVM.swift
  TaxRefundCalculator/ExchangePage/ExchangeView.swift
  TaxRefundCalculator/Models/ExchangeRateModel.swift
  TaxRefundCalculator/SavedPage/SavedCardCell.swift
  TaxRefundCalculator/SavedPage/SavedVC.swift
  TaxRefundCalculator/SavedPage/SavedView.swift
Labels: Feat, UI

#15 Feat: 시작화면, 계산화면, 설정화면 UI 구현 완료
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/Modals/CountryModal.swift
  TaxRefundCalculator/Modals/LanguageModal.swift
  TaxRefundCalculator/SceneDelegate.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/SettingPage/SettingVM.swift
  TaxRefundCalculator/SettingPage/SettingView.swift
  TaxRefundCalculator/StartPage/StartPageVC.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
  TaxRefundCalculator/StartPage/StartPageView.swift
Labels: Feat, UI

#18 Feat: API 테스트 및 보안설정
  .gitignore
  TaxRefundCalculator/API/APIKeyManager.swift
  TaxRefundCalculator/API/ExchangeRateAPIService.swift
  TaxRefundCalculator/ExchangePage/ExchangeVC.swift
  TaxRefundCalculator/Models/ExchangeAPIModel.swift
  TaxRefundCalculator/SceneDelegate.swift
  TaxRefundCalculator/TabBar/TabBarController.swift
  TaxRefundCalculator/Utils/DateUtils.swift
Labels: fix, Feat

#22 Fix: 탭바 내비바 영역 제거
  TaxRefundCalculator/TabBar/TabBarController.swift
Labels: fix, Warning

#24 Feat: 파이어베이스-API 연동
  TaxRefundCalculator/API/ExchangeRateAPIService.swift
  TaxRefundCalculator/API/FirebaseExchangeService.swift
  TaxRefundCalculator/ExchangePage/ExchangeCell.swift
  TaxRefundCalculator/ExchangePage/ExchangeVC.swift
  TaxRefundCalculator/ExchangePage/ExchangeVM.swift
  TaxRefundCalculator/ExchangePage/ExchangeView.swift
  TaxRefundCalculator/Models/ExchangeAPIModel.swift
  TaxRefundCalculator/TabBar/TabBarController.swift
  TaxRefundCalculator/Utils/Double+Formatted.swift
  TaxRefundCalculator/Utils/String+FlagEmoji.swift
Labels: Feat

#26 Faet: 계산화면에서 저장된 국가정보 로드 구현
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/CalculatePage/CalculateVM.swift
  TaxRefundCalculator/Modals/CountryModal.swift
  TaxRefundCalculator/Models/CountryMatching.swift
  TaxRefundCalculator/Models/RefundCondition.swift
  TaxRefundCalculator/Models/UserDefaults.swift
  TaxRefundCalculator/SceneDelegate.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/StartPage/StartPageVC.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
  TaxRefundCalculator/TabBar/TabBarController.swift
Labels: Feat
