Repository TaxRefundCalculator/TaxRefundCalculator, pull requests merged in 2025-08, with the labels that each got.

#135 Update: 🚀 v1.0.4 업데이트
  README.md
  TaxRefundCalculator.xcodeproj/project.pbxproj
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/ko.lproj/Localizable.strings
Labels: Update

#138 Fix: 데이터 싱크 후 화면 전환 처리 & TimeZone UTC 기준 통일
  TaxRefundCalculator/API/ExchangeRateAPIService.swift
  TaxRefundCalculator/API/ExchangeSyncManager.swift
  TaxRefundCalculator/API/FirebaseExchangeService.swift
  TaxRefundCalculator/Application/SceneDelegate.swift
  TaxRefundCalculator/ExchangePage/ExchangeVC.swift
  TaxRefundCalculator/ExchangePage/ExchangeVM.swift
  TaxRefundCalculator/SavedPage/SavedView.swift
  TaxRefundCalculator/SettingPage/SettingVM.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
  TaxRefundCalculator/TabBar/TabBarController.swift
  TaxRefundCalculator/Utils/DateUtils.swift
Labels: bug, fix

#143 Update README.md
  README.md
Labels: Update

#146 Fix: 환율 API가 호출되지 않던 문제 해결 및 버전 정보 업데이트
  TaxRefundCalculator.xcodeproj/project.pbxproj
  TaxRefundCalculator/SettingPage/SettingVC.swift
Labels: bug, Update, fix, Warning

#147 Update: 🚀 v1.0.6 업데이트
  TaxRefundCalculator.xcodeproj/project.pbxproj
  TaxRefundCalculator/SettingPage/SettingVC.swift
Labels: Update

#148 Update README.md
  README.md
Labels: Update

#149 Update README.md
  README.md
Labels: Update
