Repository TaxRefundCalculator/TaxRefundCalculator, pull requests merged in 2025-07, with the labels that each got.

#103 Feat: 설정탭에서 통화 중복선택 방지 예외처리 구현
  TaxRefundCalculator.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TaxRefundCalculator/Modals/CountryModal.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/SettingPage/SettingVM.swift
Labels: Feat

#105 Fix: 업데이트 날짜 최신화
  TaxRefundCalculator/SettingPage/SettingVC.swift
Labels: Update

#107 Update: 🚀 1.0.1 업데이트
  TaxRefundCalculator.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TaxRefundCalculator/Modals/CountryModal.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/SettingPage/SettingVM.swift
  TaxRefundCalculator/StartPage/StartPageVC.swift
  TaxRefundCalculator/StartPage/StartPageVM.swift
  TaxRefundCalculator/de.lproj/Localizable.strings
  TaxRefundCalculator/en.lproj/Localizable.strings
  TaxRefundCalculator/es.lproj/Localizable.strings
  TaxRefundCalculator/fr.lproj/Localizable.strings
  TaxRefundCalculator/it.lproj/Localizable.strings
  TaxRefundCalculator/ja.lproj/Localizable.strings
  TaxRefundCalculator/ko.lproj/Localizable.strings
  TaxRefundCalculator/ru.lproj/Localizable.strings
Labels: Update

#100 Fix: 기록 모달 UI 및 폴더구조 수정, 리드미 보완
  README.md
  TaxRefundCalculator.xcodeproj/project.pbxproj
  TaxRefundCalculator/Application/AppDelegate.swift
  TaxRefundCalculator/Application/SceneDelegate.swift
  TaxRefundCalculator/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/AppIcon.appiconset/darkIcon.png
  TaxRefundCalculator/Resources/Assets.xcassets/AppIcon.appiconset/lightIcon.png
  TaxRefundCalculator/Resources/Assets.xcassets/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/bgPrimary.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/bgSecondary.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/bodyText.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/border.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/currency.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/downRed.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/grayBtn.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/mainTeal.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/placeholder.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/primaryText.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/subButton.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/subText.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/tabActive.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/tabInactive.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/textForGreen.colorset/Contents.json
  TaxRefundCalculator/Resources/Assets.xcassets/upGreen.colorset/Contents.json
  TaxRefundCalculator/Resources/Base.lproj/LaunchScreen.storyboard
  TaxRefundCalculator/SavedPage/SavedModalVC.swift
  TaxRefundCalculator/SavedPage/SavedModalVM.swift
  TaxRefundCalculator/StartPage/StartPageVC.swift
  TaxRefundCalculator/SupportingFiles/GoogleService-Info.plist
  TaxRefundCalculator/SupportingFiles/Info.plist
  TaxRefundCalculator/SupportingFiles/InfoPlist.xcstrings
  TaxRefundCalculator/de.lproj/Localizable.strings
  TaxRefundCalculator/en.lproj/Localizable.strings
  TaxRefundCalculator/es.lproj/Localizable.strings
  TaxRefundCalculator/fr.lproj/Localizable.strings
  TaxRefundCalculator/it.lproj/Localizable.strings
  TaxRefundCalculator/ja.lproj/Localizable.strings
  TaxRefundCalculator/ko.lproj/Localizable.strings
  TaxRefundCalculator/ru.lproj/Localizable.strings
Labels: documentation, fix, Feat

#116 Feat: 최소 구매금액 검증하는 로직 2종 구현, 환급정책 모달 리팩토링
  TaxRefundCalculator.xcodeproj/project.pbxproj
  TaxRefundCalculator/CalculatePage/CalculateVC.swift
  TaxRefundCalculator/Modals/RefundModal.swift
  TaxRefundCalculator/SettingPage/SettingVC.swift
  TaxRefundCalculator/de.lproj/Localizable.strings
  TaxRefundCalculator/en.lproj/Localizable.strings
  TaxRefundCalculator/es.lproj/Localizable.strings
  TaxRefundCalculator/fr.lproj/Localizable.strings
  TaxRefundCalculator/it.lproj/Localizable.strings
  TaxRefundCalculator/ja.lproj/Localizable.strings
  TaxRefundCalculator/ko.lproj/Localizable.strings
  TaxRefundCalculator/ru.lproj/Localizable.strings
Labels: bug, refactor, Feat, UI

#128 Update README.md
  README.md
Labels: Update

#129 Fix: 용어 통일
  TaxRefundCalculator/ko.lproj/Localizable.strings
Labels: refactor
